import { WorkPack } from '../types';

export const DEFAULT_WORKPACKS: WorkPack[] = [
  {
    id: 'wp-industrial-equipment',
    name: 'Industrial Equipment Inspection',
    industry: 'Manufacturing & Heavy Industry',
    description: 'Comprehensive mechanical, electrical, and safety validation for industrial motor drive units, pumps, and control enclosures.',
    equipmentType: 'Three-Phase Motor & Variable Frequency Drive',
    version: '2.4.0',
    inspectionObjectives: [
      'Verify physical asset identity, rating plate, and serial number against inventory',
      'Ensure high-voltage and arc flash safety labeling are intact and legible',
      'Inspect physical integrity of terminal box, cooling fins, and ground bonding',
      'Verify isolation switches and status indicators are in compliant operational state',
      'Capture verifiable visual and OCR evidence for compliance sign-off',
    ],
    acceptableConditions: [
      'Equipment rating plate legible with clear model and serial numbers',
      'High Voltage / Arc Flash safety labels visible and unblemished',
      'No signs of thermal discoloration or bearing oil leakage on housing',
      'Ground bonding conductor firmly affixed without corrosion',
      'Cooling fins clear of dust and debris obstruction',
    ],
    escalationConditions: [
      'Missing or illegible DANGER / HIGH VOLTAGE warning label (Immediate safety stop)',
      'Serial number mismatch or unidentifiable asset tag',
      'Visible burning, scorch marks, or physical housing fracture',
      'Ground wire disconnected or severed',
    ],
    metadata: {
      author: 'SnapOps Enterprise Safety Standards Board',
      targetHardwareProfile: 'Snapdragon X Series / HP Elite Dragonfly Edge',
      lastUpdated: '2026-03-15',
      tags: ['Industrial', 'Electrical', 'OSHA', 'Motor', 'VFD'],
    },
    steps: [
      {
        id: 'step-1-identify',
        order: 1,
        title: 'Identify Equipment & Unit Exterior',
        instruction: 'Aim the camera at the entire equipment unit to establish visual asset identification and general physical condition.',
        targetArea: 'Full unit view / chassis',
        requiredObservations: [
          'Chassis frame and mounting base intact',
          'Unit appears undamaged and free of liquid intrusion',
        ],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-identify-equip',
            ruleName: 'Equipment Presence',
            description: 'Equipment chassis or motor housing must be clearly in frame',
            targetComponent: 'motor',
            minimumConfidence: 0.75,
            severityIfFailed: 'warning',
          },
        ],
        guidanceOnFail: 'Step back to bring the full equipment silhouette into the frame.',
        allowManualOverride: true,
      },
      {
        id: 'step-2-nameplate',
        order: 2,
        title: 'Read Model & Serial Information',
        instruction: 'Move camera within 15-30cm of the manufacturer rating plate to read model number, serial number, and electrical ratings.',
        targetArea: 'Metal rating plate / manufacturer spec tag',
        requiredObservations: [
          'Serial number clearly legible',
          'Model designation and voltage rating visible',
        ],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-ocr-serial',
            ruleName: 'Serial Number Text Extraction',
            description: 'OCR must detect alphanumeric serial/model tag',
            requiredKeywordRegex: '[A-Z0-9]{4,}',
            minimumConfidence: 0.8,
            severityIfFailed: 'critical',
          },
        ],
        guidanceOnFail: 'Move camera closer to the rating plate. Ensure lighting prevents glare on reflective metal.',
        allowManualOverride: true,
      },
      {
        id: 'step-3-safetylabel',
        order: 3,
        title: 'Verify Required Safety Labeling',
        instruction: 'Inspect the electrical enclosure for required safety warnings (e.g. HIGH VOLTAGE, DANGER, CAUTION, or ARC FLASH).',
        targetArea: 'Electrical enclosure door / terminal cover',
        requiredObservations: [
          'Safety warning label present and clearly legible',
          'No peeling, fading, or vandalism on safety placards',
        ],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-safety-label',
            ruleName: 'Safety Warning Placard Detection',
            description: 'Must detect warning keywords (DANGER, HIGH VOLTAGE, CAUTION, or NOTICE)',
            requiredKeywordRegex: '(DANGER|VOLTAGE|CAUTION|WARNING|NOTICE|ARC FLASH)',
            minimumConfidence: 0.85,
            severityIfFailed: 'critical',
          },
        ],
        guidanceOnFail: 'Pan camera to the electrical enclosure front door or disconnect switch where hazard labels are placed.',
        allowManualOverride: true,
      },
      {
        id: 'step-4-components',
        order: 4,
        title: 'Inspect Visible Components & Housing',
        instruction: 'Check cooling fan cowl, ventilation louvers, drive shaft coupling guard, and terminal junction box.',
        targetArea: 'Cooling fan shroud, fin array, and junction seal',
        requiredObservations: [
          'Cooling airflow vents free from obstruction',
          'Junction box cover bolts secured',
          'No visible fluid seepage or excessive corrosion',
        ],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-cooling-integrity',
            ruleName: 'Component Housing Integrity',
            description: 'Inspect cooling structure and terminal enclosure',
            targetComponent: 'cooling',
            minimumConfidence: 0.7,
            severityIfFailed: 'warning',
          },
        ],
        guidanceOnFail: 'Focus camera on the fan shroud and cooling fins to verify airflow path is unobstructed.',
        allowManualOverride: true,
      },
      {
        id: 'step-5-grounding',
        order: 5,
        title: 'Verify Ground Bonding & Status',
        instruction: 'Verify external green/copper equipment grounding conductor connection to the chassis grounding lug.',
        targetArea: 'Grounding lug / PE conductor clamp',
        requiredObservations: [
          'Earth grounding conductor securely clamped',
          'No oxidization on bonding contact points',
        ],
        requiredEvidence: true,
        requiresAIValidation: false,
        validationRules: [],
        guidanceOnFail: 'Check the grounding screw near the base of the motor housing.',
        allowManualOverride: true,
      },
      {
        id: 'step-6-review-signoff',
        order: 6,
        title: 'Review Findings & Final Evidence',
        instruction: 'Review all captured evidence, confirm any detected warnings, and prepare the final compliance audit report.',
        targetArea: 'Overall system audit review',
        requiredObservations: [
          'All required evidence photos captured',
          'Any detected anomalies resolved or documented',
        ],
        requiredEvidence: false,
        requiresAIValidation: false,
        validationRules: [],
        guidanceOnFail: 'Review the evidence gallery to ensure all necessary steps have proof.',
        allowManualOverride: false,
      },
    ],
  },
  {
    id: 'wp-solar-inverter',
    name: 'Solar Inverter & High-Voltage DC Disconnect',
    industry: 'Renewable Energy & Utilities',
    description: 'Inspection procedure for utility-scale and commercial string inverters, DC disconnect switches, and combiner enclosures.',
    equipmentType: 'Commercial Solar String Inverter (1000V DC)',
    version: '1.8.0',
    inspectionObjectives: [
      'Validate DC disconnect switch position (LOCK-OUT / TAG-OUT / ON / OFF)',
      'Confirm high-voltage 1000V DC warning decals are intact',
      'Inspect MC4 solar connector strings for thermal damage or water ingress',
      'Check inverter LCD / LED status code indicators',
    ],
    acceptableConditions: [
      'Inverter status indicator green (Normal / Grid Synchronized)',
      'DC disconnect handle locked in prescribed position',
      'Enclosure gasket sealed with IP65 compression locks latched',
    ],
    escalationConditions: [
      'Fault indicator red or error code displayed on screen',
      'Melted or scorched MC4 cable connectors',
      'Arc flash warning missing on high-voltage compartment',
    ],
    metadata: {
      author: 'CleanGrid Operations & Maintenance',
      targetHardwareProfile: 'Snapdragon X Series / Rugged Field Tablet',
      lastUpdated: '2026-02-28',
      tags: ['Solar', 'Inverter', 'High-Voltage', 'DC Disconnect', 'Energy'],
    },
    steps: [
      {
        id: 'sol-step-1',
        order: 1,
        title: 'Identify Inverter Unit & Display State',
        instruction: 'Frame the inverter main cabinet including the front status display panel.',
        targetArea: 'Front panel display',
        requiredObservations: ['Inverter model visible', 'Status LEDs or LCD legible'],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-sol-status',
            ruleName: 'Inverter Presence',
            description: 'Cabinet and display must be visible',
            targetComponent: 'inverter',
            severityIfFailed: 'warning',
          },
        ],
        guidanceOnFail: 'Center the inverter front face in the camera frame.',
        allowManualOverride: true,
      },
      {
        id: 'sol-step-2',
        order: 2,
        title: 'Inspect DC Disconnect Switch Position',
        instruction: 'Move camera to the rotary DC disconnect switch located at the bottom or side of the inverter.',
        targetArea: 'DC disconnect switch handle and labeling',
        requiredObservations: ['Switch position clearly discernible (ON / OFF / TRIP)'],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-sol-switch',
            ruleName: 'Switch Position Text',
            description: 'Detect switch state markings (ON, OFF, or DISCONNECT)',
            requiredKeywordRegex: '(ON|OFF|DISCONNECT|DC SWITCH)',
            minimumConfidence: 0.8,
            severityIfFailed: 'critical',
          },
        ],
        guidanceOnFail: 'Point camera directly at the DC disconnect rotary switch label.',
        allowManualOverride: true,
      },
      {
        id: 'sol-step-3',
        order: 3,
        title: 'Verify High-Voltage DC Hazard Placard',
        instruction: 'Verify the mandatory 1000V DC / Arc Flash hazard placard on the cable entry zone.',
        targetArea: 'Cable entry gland plate hazard label',
        requiredObservations: ['Hazard symbol and voltage rating visible'],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-sol-hazard',
            ruleName: 'High Voltage Warning Sign',
            description: 'Must detect DANGER, HIGH VOLTAGE, or DC rating',
            requiredKeywordRegex: '(DANGER|HIGH VOLTAGE|1000V|ARC FLASH)',
            minimumConfidence: 0.85,
            severityIfFailed: 'critical',
          },
        ],
        guidanceOnFail: 'Move camera closer to the warning label near the lower wiring compartment.',
        allowManualOverride: true,
      },
    ],
  },
  {
    id: 'wp-conveyor-estop',
    name: 'Automated Conveyor & E-Stop Safety System',
    industry: 'Logistics & Warehousing',
    description: 'Operational safety verification for high-speed sortation conveyors, emergency stop pull-cords, and optical light curtains.',
    equipmentType: 'Sortation Conveyor System',
    version: '3.1.0',
    inspectionObjectives: [
      'Verify emergency stop pushbuttons are unblocked and illuminated',
      'Inspect safety interlock sensors and photoelectric alignment',
      'Confirm conveyor roller bearings and safety perimeter guards are fastened',
    ],
    acceptableConditions: [
      'All red mushroom E-Stop buttons popped up (untriggered)',
      'Safety yellow perimeter kickplates and barrier netting intact',
      'Emergency stop signage clearly legible above each station',
    ],
    escalationConditions: [
      'Blocked access to any emergency stop button',
      'Missing or broken E-Stop label',
      'Damaged optical light curtain bracket',
    ],
    metadata: {
      author: 'Global Logistics Safety Directorate',
      targetHardwareProfile: 'Snapdragon X Series / HP Elite Dragonfly Edge',
      lastUpdated: '2026-01-20',
      tags: ['Logistics', 'Conveyor', 'E-Stop', 'Safety Interlock'],
    },
    steps: [
      {
        id: 'conv-step-1',
        order: 1,
        title: 'Verify Emergency Stop Button & Signage',
        instruction: 'Aim camera at the Emergency Stop station. Ensure red mushroom head and yellow background ring are clearly visible.',
        targetArea: 'E-Stop pushbutton station',
        requiredObservations: ['Red button head intact', 'EMERGENCY STOP label legible'],
        requiredEvidence: true,
        requiresAIValidation: true,
        validationRules: [
          {
            id: 'rule-conv-estop',
            ruleName: 'E-Stop Signage Recognition',
            description: 'Detect EMERGENCY STOP or STOP signage',
            requiredKeywordRegex: '(EMERGENCY|STOP|E-STOP)',
            minimumConfidence: 0.85,
            severityIfFailed: 'critical',
          },
        ],
        guidanceOnFail: 'Align camera with the yellow E-Stop placard and red mushroom button.',
        allowManualOverride: true,
      },
      {
        id: 'conv-step-2',
        order: 2,
        title: 'Inspect Roller Guard Barrier',
        instruction: 'Examine the nip-point guarding along the conveyor bed to ensure no safety mesh is bent or unbolted.',
        targetArea: 'Conveyor side guardrail & mesh',
        requiredObservations: ['Guard mesh secured with bolts', 'No nip-point exposed'],
        requiredEvidence: true,
        requiresAIValidation: false,
        validationRules: [],
        guidanceOnFail: 'Capture a clear angle of the side barrier fastening points.',
        allowManualOverride: true,
      },
    ],
  },
];
